################################################################################
# 自动生成的文件。不要编辑！
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_comp.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_crc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_crc_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dac.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dac_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_exti.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gpio.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gtzc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_hsem.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2s.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_ipcc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_irda.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_iwdg.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_lptim.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pka.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rng.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rng_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smartcard.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smartcard_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smbus.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smbus_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_spi.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_spi_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_subghz.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_usart.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_usart_ex.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_wwdg.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_adc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_comp.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_crc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_dac.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_dma.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_exti.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_gpio.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_i2c.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_lptim.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_lpuart.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_pka.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_pwr.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rcc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rng.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rtc.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_spi.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_tim.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_usart.c \
../libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_utils.c 

OBJS += \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_comp.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_crc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_crc_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dac.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dac_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_exti.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gpio.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gtzc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_hsem.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2s.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_ipcc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_irda.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_iwdg.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_lptim.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pka.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rng.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rng_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smartcard.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smartcard_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smbus.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smbus_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_spi.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_spi_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_subghz.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_usart.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_usart_ex.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_wwdg.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_adc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_comp.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_crc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_dac.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_dma.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_exti.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_gpio.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_i2c.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_lptim.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_lpuart.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_pka.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_pwr.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rcc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rng.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rtc.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_spi.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_tim.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_usart.o \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_utils.o 

C_DEPS += \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_comp.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_crc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_crc_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cryp_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dac.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dac_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_exti.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gpio.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gtzc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_hsem.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2s.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_ipcc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_irda.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_iwdg.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_lptim.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pka.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rng.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rng_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smartcard.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smartcard_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smbus.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_smbus_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_spi.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_spi_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_subghz.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_usart.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_usart_ex.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_wwdg.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_adc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_comp.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_crc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_dac.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_dma.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_exti.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_gpio.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_i2c.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_lptim.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_lpuart.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_pka.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_pwr.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rcc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rng.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_rtc.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_spi.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_tim.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_usart.d \
./libraries/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
libraries/STM32WLxx_HAL_Driver/Src/%.o: ../libraries/STM32WLxx_HAL_Driver/Src/%.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DSOC_FAMILY_STM32 -DSOC_SERIES_STM32WL -DUSE_HAL_DRIVER -DSTM32WLE5xx -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\drivers" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\drivers\include" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\drivers\include\wl" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\libraries\CMSIS\Device\ST\STM32WLxx\Include" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\libraries\CMSIS\Include" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\libraries\CMSIS\RTOS\Template" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\libraries\STM32WLxx_HAL_Driver\Inc" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\libraries\STM32WLxx_HAL_Driver\Inc\Legacy" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\applications" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\cubemx" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\cubemx\Inc" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\applications\SubGHz\App" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\applications\SubGHz\common" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\applications\SubGHz\SubGHz_Phy" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\applications\SubGHz\Target" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\applications\SubGHz\SubGHz_Phy\stm32_radio_driver" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\components\drivers\include" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\components\finsh" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\components\libc\compilers\common\include" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\components\libc\compilers\newlib" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\components\libc\posix\io\poll" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\components\libc\posix\io\stdio" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\components\libc\posix\ipc" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\components\utilities\ulog" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\include" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\libcpu\arm\common" -I"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rt-thread\libcpu\arm\cortex-m4" -include"D:\RT-ThreadStudio\workspace\STM32WLE5CBU6_RT-Thread\rtconfig_preinc.h" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

